version: '3.8'

services:
  app:
    image: your-docker-username/realtracker:latest
    restart: always
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - ./storage:/var/www/storage
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
